name: APK Compilation (Android)

on:
  workflow_dispatch:

env:
  JAVA_VERSION: "17.x"
  FLUTTER_CHANNEL: "stable"

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: "gradle"
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build APKs
        run: flutter build apk --debug --split-per-abi

  upload:
    name: "Upload"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apks
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk
